### ISSUE TITLE
Feature roadmap to 1.0

### ISSUE THREAD

**Issue by ltackett** [ltackett/roygbiv#1]
# Roadmap to v1
### Features

The concept for this whole thing is pretty simple; Do good stuff? Clip up. Do bad stuff? Clip down. I'm already using the prototype, but it's pretty barebones. Here's a list of features I'd like to hit before release:

* [ ] Authentication
* [ ] Users accounts
* [ ] Dashboard
* [ ] Families
* [ ] Link Families with other users
* [ ] Read-only link
* [ ] Notes
* [ ] Routine charts
* [ ] Auto-archiving previous day’s charts and notes
* [ ] Simple analytics
* [ ] Custom colors and emoji
* [ ] Custom reward emoji
* [ ] Webhooks for clip up, clip down, and each chart position
